parameters:
#    alex_mnc.example.class: Alex\Bundle\MNCBundle\Example

services:
#    alex_mnc.example:
#        class: %alex_mnc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
